.____                                       
|    |   _____    ________________    ____  
|    |   \__  \ _/ __ \_  __ \__  \  /    \ 
|    |___ / __ \\  ___/|  | \// __ \|   |  \
|_______ (____  /\___  >__|  (____  /___|  /
        \/    \/     \/           \/     \/ 

MUD napędzany parą

Witaj na Laeran. Na razie jesteśmy jeszcze
we wczesnej fazie rozwoju, wszystko może
ulec zmianie.

Wprowadź imię postaci albo zamknij połączenie.
Jeżeli chcesz stworzyć nową postać, wpisz wybrane
przez siebie imię postaci.

Imię postaci: 