.____                                       
|    |   _____    ________________    ____  
|    |   \__  \ _/ __ \_  __ \__  \  /    \ 
|    |___ / __ \\  ___/|  | \// __ \|   |  \
|_______ (____  /\___  >__|  (____  /___|  /
        \/    \/     \/           \/     \/ 

MUD napędzany parą

Witaj na Laeran. Na razie jesteśmy jeszcze
we wczesnej fazie rozwoju, wszystko może
ulec zmianie.

Wprowadź nazwę konta albo zamknij połączenie.
Jeżeli chcesz założyć nowe konto, wpisz wybraną
przez siebie nazwę konta.

Nazwa konta: 